name: fluttermasktest
description: A new Flutter application.
authors:
  - Dreamwalker(aristojeff@gmail.com)
homepage: https://github.com/JAICHANGPARK

version: 1.3.5+24

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.0+4
  hive: any
  hive_flutter: any
  path_provider: any
  shared_preferences: ^0.5.6
  google_fonts: any
  webview_flutter: ^0.3.19+9
  firebase_core: any
  firebase_remote_config: ^0.3.0+3
  firebase_messaging: ^6.0.12

  location: ^2.5.3

  kopo: ^0.1.1
  package_info: ^0.4.0+14
  url_launcher: ^5.4.2
  firebase_analytics: ^5.0.11
  google_nav_bar: ^2.0.1
  line_icons: any

  avatar_glow: any
  sliding_up_panel: ^1.0.0

  flutter_map: any
  flutter_map_marker_cluster: any

  share: any
  intl: ^0.16.1
  async: ^2.4.0

  provider: any


dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  hive_generator: any
  build_runner: any

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icon/icons2/
    - assets/files/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icons2/playstore.png"